import type { NextPage } from "next";
import Head from "next/head";
import CounterSection from "src/components/CounterSection";
import PageLayout from "src/components/layout/PageLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>next js boiler plate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <CounterSection />
        <div className="text-blue-200">driver</div>
      </PageLayout>
    </div>
  );
};

export default Home;
